<?php include "includes/header.php" ?>
<?php include "includes/navigation.php" ?>

<section class="section-hero overlay inner-page bg-image" style="background-image: url('images/la-gallery/banner4.jpeg');" id="home-section">
	<div class="container">
		<div class="row">
			<div class="col-md-7">
				<h1 class="text-white font-weight-bold">Privacy Policy</h1>				
				<div class="custom-breadcrumbs">					
				</div>
			</div>
		</div>
	</div>
</section>

<section class="site-section">
	<div class="container">		
		<div class="row">
			<div class="col-lg-12">
				<div class="mb-5" style="font-size: 24px; color: #000000; text-align: justify;">
					<!-- Terms -->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>Terms</strong></h2>
					<p>This document is an electronic record in terms of the amended Information Technology Act, 2000 and rules and regulation made thereunder. This electronic record is generated by a computer system and does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the Terms for access or usage of OTAF overseas Private Limited via Labouradda Portals. This document meets the stipulations and conditions mentioned in Section 65B (2) of the Indian Evidence Act, 1872. <br><br>

					This is an agreement between OTAF Overseas Pvt. Ltd., a company incorporated under the Companies Act 1956 with its registered office at Akaknsha, F- 501, Savvy Swaraj,Gota - Ahmedabad , Gujarat, the owner and operator of www.labouradda.net (the "Labouradda Site"), the Labouradda Application Software "Labouradda Mobile App", including collectively, including all content provided by Labouradda through Labouradda Application and the Labouradda Site, the "Labouradda Service", or the "Service", and you ("you" or "You"), a user of the Service. BY USING THE SERVICE, YOU ACKNOWLEDGE AND AGREE TO THESE TERMS OF SERVICE, TERMS OF USE FOR SEARCH SERVICES, INFRINGEMENT POLICY, TERMS FOR UPI, SOFTWARE LICENSE AGREEMENT,SOFTWARE LICENSE AND LABOURADDA'S PRIVACY POLICY, WHICH CAN BE FOUND AT PRIVACY POLICY AND WHICH ARE INCORPORATED HEREIN BY REFERENCE. If you choose to not agree with any of these terms, you may not use the Service. <br><br>
				</p>

					<!-- Labouradda Service -->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>Labouradda Service</strong></h2>
					<p>These Terms of Service apply to all users of Labouradda Platform. Information provided by our users through the Labouradda Platform may contain links to third party websites that are not owned or controlled by Labouradda. Labouradda has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party websites. Also, Labouradda does not assume any liability for any mistakes, misstatements of law, defamation, omissions, falsehood, obscenity, pornography or profanity in the statements, opinions, representations or any other form of third party content on the Site. In addition, Labouradda will not and cannot censor or edit the content of any third-party site. By using the Service, you expressly acknowledge and agree that Labouradda shall not be responsible for any damages, claims or other liability arising from or related to your use of any third-party website. You understand that the information and opinions in the third party content represent solely the thoughts of the author and is neither endorsed by nor does it necessarily reflect Labouradda's belief.
				</p>

					<!-- Errors, Corrections, and Right to Modify or Discontinue Service and Sites: -->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>Errors, Corrections, and Right to Modify or Discontinue Service and Sites</strong></h2>
					<p>We do not represent or warrant that the Labouradda Platform will be error-free, free of viruses or other harmful components, or that defects will be corrected. We do not represent or warrant that the information available on or through the Labouradda Platform will be correct, accurate, timely or otherwise reliable. We may make changes to the features, functionality or content of the Labouradda Platform at any time. We reserve the right in our sole discretion to edit or delete any documents, information or other content appearing on the  Labouradda Platform. Labouradda reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Services and/or Sites (or any part thereof) with or without notice. Labouradda shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Service or any Sites.
				</p>

					<!-- Labouradda Platform Access -->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>Labouradda Platform Access</strong></h2>
					<p>A. Subject to your compliance with these Terms of Service, Labouradda hereby grants you permission to use the Service, provided that:</p>

					<ol>
						<li>Your use of the Service as permitted is solely for your personal use, and you are not permitted to resell or charge others for use of or access to the Service, or in any other manner inconsistent with these Terms of Service;</li>
						<li>you will not duplicate, transfer, give access to, copy or distribute any part of the Service in any medium without Labouradda's prior written authorization;</li>
						<li>you will not attempt to reverse engineer, alter or modify any part of the Service;</li>
						<li>you will otherwise comply with the terms and conditions of these Terms of Service and Privacy Policy. The Application is currently made available to you free of charge for your personal, non-commercial use.  Labouradda reserves the right to amend or withdraw the Application, or charge for the application or service provided to you in accordance with these Labouradda Mobile App terms, at any time and for any reason.</li>
					</ol>
					<p>B. In order to access and use the features of the Service, you acknowledge and agree that you will have to provide Labouradda with your mobile phone number. You expressly acknowledge and agree that in order to provide the Service, Labouradda may periodically access your contact list and/or address book on your mobile device to find and keep track of mobile phone numbers of other users of the Service. When providing your mobile phone number, you must provide accurate and complete information. You hereby give your express consent to Labouradda to access your contact list and/or address book for mobile phone numbers in order to provide and use the Service. You must notify Labouradda immediately of any breach of security or unauthorized use of your mobile phone. For removal of doubts it is clarified that, Labouradda is not liable for any loss or damage caused by any unauthorized use of your account, however you would be liable for any losses or damage caused to Labouradda Platform including but not limited to any claims made on Labouradda or others due to such unauthorized use.</p>

					<p>C. You agree not to use or upload, post or submit any content that contains software viruses or any computer code, files, or programs designed to interrupt, destroy, or limit functionality of the Platform or of any computer software, hardware, or telecommunications equipment. You also agree to not decipher, decompile, disassemble, use sniffers (except Ethereal, tcpdump or HTTPWatch in general) or reverse engineer any of the software comprising or in any way making up part of the Labouradda Platform. We have to disallow use of request modification tools such as fiddler or whisker, or the like or any other such tools activities that are meant to explore or harm, penetrate or test the application. You must secure our permission before you measure, test, health check or otherwise monitor any network equipment, servers or assets hosted on our domain. You agree not to collect or harvest any personally identifiable information, including phone number, from the Service, nor to use the communication systems provided by the Service for any commercial solicitation or spam purposes. You agree not to spam, or solicit for commercial purposes, any users of the Service. You agree not to create any data back up of the content that is available to you by use of the Labouradda Platform or Labouradda Mobile App. or use of Labouradda Platform that is available through any other mediums.</p>

					<!-- AVAILABILITY -->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>AVAILABILITY</strong></h2>
					<ol>
						<li>Labouradda will use reasonable efforts to make the Application available at all times. However you acknowledge the Application is provided over the internet and mobile networks and so the quality and availability of the Application may be affected by factors outside Labouradda's reasonable control. Labouradda does not accept any responsibility whatsoever for unavailability of the Application, or any difficulty or inability to download or access content or any other communication system failure which may result in the Application being unavailable.</li>
						<li>Labouradda will not be responsible for any support or maintenance for the Application.</li>						
					</ol>					


					<!-- SYSTEM REQUIREMENTS -->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>SYSTEM REQUIREMENTS</strong></h2>
					<ol>
						<li>In order to use the Application, you are required to have a compatible mobile telephone or handheld device, internet access, and the necessary minimum specifications ('Software Requirements').</li>
						<li>The Software Requirements for downloading the Labouradda  Mobile App would vary as per the mobile platform. The Labouradda Mobile App would be available in English Language as of now.</li>
						<li>The version of the Application software may be upgraded from time to time to add support for new functions and services.</li>
					</ol>	

					<!-- Intellectual Property Rights -->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>Intellectual Property Rights</strong></h2>
					<p>The Labouradda name, logos, all related products and service names, design marks, slogans, trademarks, service marks, copyright, database rights (and other intellectual property rights of any nature in the Application) together with the underlying software code in the App ("Intellectual Property") is managed by and used under license by Siddarth Asthana to OTAF Overseas Pvt. Ltd. or its subsidiaries or affiliate companies. All other Intellectual Properties herein are the property of their respective owners. All copies that you make of the Materials on any of the Media must bear any copyright, trademark or other proprietary notice located on the respective Media that pertains to the material being copied. You are not authorized to use Labouradda's Intellectual Property in any advertising, publicity or in any other commercial manner. Reference to any products, services, processes or other information, by trade name, trademark, manufacturer, supplier or otherwise does not constitute or imply endorsement, sponsorship or recommendation thereof by Labouradda. <br><br>

					For removal of doubts, it is clarified that, by accepting these terms, you hereby waive and grant to Labouradda all rights including intellectual property rights and also "moral rights" in the Reviews, Ratings and Comments posted by you at Labouradda through any of mediums of Labouradda and that Labouradda is free to use all such Review, Ratings and Comments as per its (Labouradda's) requirements from time to time.
					</p>



					<!-- User Submissions & Specific Features-->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>User Submissions & Specific Features</strong></h2>
					<p>A. Tag your Friends - (Refer Privacy Policy)<br>
					B. Ratings and Reviews - (Refer Privacy Policy)<br>
					C. In connection with Ratings and Tag your friends, you further agree that you will not:
					</p>

					<ol>
						<li>submit material that is copyrighted, protected by trade secret or otherwise subject to third party proprietary rights, including privacy and publicity rights, unless you are the owner of such rights or have permission from their rightful owner to post the material and to grant Labouradda all of the license rights granted herein;</li>
						<li>publish falsehoods or misrepresentations that could damage Labouradda or any third party;</li>
						<li>submit material that is unlawful, obscene, defamatory, libelous, threatening, harassing, hateful, racially or ethnically offensive, or encourages conduct that would be considered a criminal offense, give rise to civil liability, violate any law, or is otherwise inappropriate;</li>
						<li>post advertisements or solicitations of business;</li>
						<li>impersonate another person;</li>
						<li>send or store material containing software viruses, worms, Trojan horses or other harmful computer code, files, scripts, agents or programs;</li>
						<li>interfere with or disrupt the integrity or performance of the Service or the data contained therein; or</li>
						<li>attempt to gain unauthorized access to the Service or its related systems or networks.</li>
					</ol>




					<!-- ======================== -->
					<p>D. Adult content must be identified as such. Labouradda does not endorse any Rating and/or Review or any opinion, recommendation, or advice expressed therein, and Labouradda expressly disclaims any and all liability in connection with ratings and/or submissions. Labouradda does not permit copyright infringing activities and infringement of intellectual property rights via its Service, and Labouradda will remove all content and Ratings and/or Reviews if properly notified that such content infringes on another's intellectual property rights. To file a copyright infringement notification, please send a written communication that includes substantially the following:</p>
					<ol>
						<li>A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;</li>
						<li>Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works;</li>
						<li>Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit the service provider to locate the material, including the mobile phone number of the Labouradda Mobile App user allegedly infringing the copyrighted work;</li>
						<li>Information reasonably sufficient to permit the service provider to contact the complaining party, such as an address, telephone number, and, if available, an electronic mail address at which the complaining party may be contacted;</li>
						<li>A statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</li>
						<li>A statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed. Such takedown notices may be emailed to support at. Labouradda reserves the right to remove contents without prior notice. Labouradda may also terminate a user's access to the Service, if they are determined to be a repeat infringer, or for any or no reason, including being annoying. A repeat infringer is a User who has been notified of infringing activity more than once and/or has had a content removed from the Service more than once. Labouradda also reserves the right to decide whether content or a Rating and/or Review is appropriate and complies with these Terms of Service for violations other than copyright infringement and violations of intellectual property law, such as, but not limited to excessive length or limited interest. Labouradda may remove such contents and/or terminate a User's access for uploading such material in violation of these Terms of Service at any time, without prior notice and at its sole discretion.</li>
					</ol>



					<p>E. You understand that when using the Labouradda Platform you will be exposed to Ratings and Review submissions from a variety of sources, and that Labouradda  is not responsible for the accuracy, usefulness, safety, or intellectual property rights of or relating to such Submissions, and that such Submissions are not the responsibility of Labouradda. You further understand and acknowledge that you may be exposed to Submissions that are inaccurate, offensive, indecent, or objectionable, and you agree to waive, and hereby do waive, any legal or equitable rights or remedies you have or may have against Labouradda with respect thereto, and agree to indemnify and hold Labouradda, its officers, directors, employees, agents, affiliates, and/or licensors, harmless to the fullest extent allowed by law regarding all matters related to your use of the Labouradda Platform.</p>

					<p>F. Labouradda reserves the right to discontinue any aspect of the Labouradda Platform at any time.</p>

					<p>G. Right, But Not Obligation, to Monitor Submissions: Labouradda does not and shall not have any obligation to review Submissions, and therefore we do not guarantee the accuracy, integrity or quality of Submissions and we cannot assure you that harmful, inaccurate, deceptive, offensive, threatening, defamatory, unlawful or otherwise objectionable Submissions will not appear on our Service. We do, however, reserve the right to review any or all Submissions in our sole discretion. In addition, we reserve the right to alter, edit or remove any Submissions, in whole or in part, at our sole discretion.</p>

					<p>H. Your Use of Submissions Posted by Others. You may not use, copy, reproduce, distribute, publish, display or perform, create derivative works of, transmit, sell, or in any way exploit any of the Submissions posted by others except as expressly set forth in these Terms of Use.</p>



					<!-- WARRANTY -->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>WARRANTY</strong></h2>
					<p><strong>THE MATERIAL AND THE MEDIA USED TO PROVIDE THE MATERIAL (INCLUDING THE WEBSITE ) ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. LABOURADDA DISCLAIMS, TO THE FULLEST EXTENT PERMITTED UNDER LAW, ANY WARRANTIES REGARDING THE SECURITY, RELIABILITY, TIMELINESS, ACCURACY AND PERFORMANCE OF THE MEDIA AND MATERIALS. LABOURADDA DOES NOT WARRANT THAT ANY DEFECTS OR ERRORS WILL BE CORRECTED; OR THAT THE CONTENT IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. LABOURADDA DISCLAIMS ANY AND ALL WARRANTIES TO THE FULLEST EXTENT OF THE LAW, INCLUDING ANY WARRANTIES FOR ANY INFORMATION, GOODS, OR SERVICES, OBTAINED THROUGH, ADVERTISED OR RECEIVED THROUGH ANY LINKS PROVIDED BY OR THROUGH THE MEDIA. SOME COUNTRIES OR OTHER JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU. YOU MAY ALSO HAVE OTHER RIGHTS THAT VARY FROM COUNTRY TO COUNTRY AND JURISDICTION TO JURISDICTION. IN NO EVENT SHALL LABOURADDA BE LIABLE TO ANY USER ON ACCOUNT OF SUCH USER'S USE, MISUSE OR RELIANCE ON THE MEDIA FOR ANY DAMAGES WHATSOEVER, INCLUDING DIRECT, SPECIAL, PUNITIVE, INDIRECT, CONSEQUENTIAL OR INCIDENTAL DAMAGES OR DAMAGES FOR LOSS OF PROFITS, REVENUE, USE, OR DATA WHETHER BROUGHT IN WARRANTY, CONTRACT, INTELLECTUAL PROPERTY INFRINGEMENT, TORT (INCLUDING NEGLIGENCE) OR OTHER THEORY, EVEN IF LABOURADDA IS AWARE OF OR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE, ARISING OUT OF OR CONNECTED WITH THE USE (OR INABILITY TO USE) OR PERFORMANCE OF THE MEDIA OR THE USE (OR INABILITY TO USE), RELIANCE UPON OR PERFORMANCE OF ANY MATERIAL CONTAINED IN OR ACCESSED FROM ANY MEDIA. LABOURADDA DOES NOT ASSUME ANY LEGAL LIABILITY OR RESPONSIBILITY FOR THE ACCURACY, COMPLETENESS, OR USEFULNESS OF ANY INFORMATION, APPARATUS, PRODUCT OR PROCESS DISCLOSED ON THE MEDIA OR OTHER MATERIAL ACCESSIBLE FROM THE MEDIA. THE USER OF THE MEDIA ASSUMES ALL RESPONSIBILITY AND RISK FOR THE USE OF THIS MEDIA. THE FOREGOING LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF THE ESSENTIAL PURPOSE OF ANY LIMITED REMEDY AND TO THE FULLEST EXTENT PERMITTED UNDER APPLICABLE LAW. SOME COUNTRIES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY OF CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE EXCLUSIONS MAY NOT APPLY TO ALL USERS; IN SUCH COUNTRIES LIABILITY IS LIMITED TO THE FULLEST EXTENT PERMITTED BY LAW.</strong></p>


					<!-- ADDITIONAL DISCLAIMER -->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>ADDITIONAL DISCLAIMER</strong></h2>
					<p>OTAF Overseas Private Limited (Company): Is a software company that offers innovative and technology based customized Solutions using hard wares and software that can function across the country on air. OTAF is an acronym and means "On the air functionalities (OTAF)"and is called OTAF Overseas Private Limited hereafter also referred as Company. The company has developed a unique tech enabled platform that helps in connecting a Service Seeking Consumers of Labours to a Job Seeking Labours registered online and on phone call taking note of Name, Vocation (Skillset) and Contact details purely on good faith, to increase employability of the daily wage labours of unorganized sector. The Company using hardware and Software has created (1) Labour Mandi - It's an On Line Digital Labour Mandi. It is a unique technology based on the air Digital Avatar of a typical Labour Mandi created using Geo Positioning System and connects Labours to Consumers who have registered themselves with the Company. (2) Labouradda - Mobile App: It is an android based - Mobile App developed by the company for that can be downloaded from play store by service seeking consumers of labours to connect to nearest job seeking Labours.(3) Labouradda Website (www.labouradda.net)of the On Line Digital Mandi is also connected to a web page enabled with a booking engine to be used by service seeking consumers that will connect the Service seeking consumers who have registered themselves for connecting with the nearest job seeking Labours. (4) Labouradda Call Center – is a unique Customer Relationship Management (CRM) software with multiple-portals handled by full time executives connecting a service seeking consumers of labours who have registered themselves for connecting with the nearest job seeking Labours (5)Labouradda Face book page: All our online digital Labour Mandi are also connected to a face book that has a booking engine that redirects a service seeking consumers who have registered themselves for connecting with the nearest job seeking Labours.(6) Labour Adda Dealer app is created for labour Supply Coordinators / conventional labour thekedaars. Labouradda Dealer Mobile App can be downloaded from a play Store and subscribed for use by paying a monthly subscription fee valid for 28days. It is a Unique Mobile app created for conventional thekedaars for dealing in online duties and bulk contracts as Labouradda Dealersby using the functionality of the APP subscribed by them. All our aforesaid Labouradda platforms are created to connect Service Seeking Consumers and Job Seeking daily wage labours with each other and deal them directly using own discretionary power.  Call back mobile number provided by a consumer at the time of booking is forwarded with consent of our registered service seeking consumers to our dealer’s mobile numbers of Labour Mandi all registered by us using electronic medias and information technology in good faith to increase employability of the labours of Labour Mandi.  Consumers are contacted directly by these dealers & Job seeking Labours.
					Users using any of Labouradda Platform across the following mediums i.e. through internet i.e. www.labouradda.net Website,Social Media, SMS, phone or any other medium are bound by this additional disclaimer wherein they are cautioned to make proper enquiry before they (Users) rely, act upon or enter into any transaction (any kind or any sort of transaction including but not limited to monetary transaction) with the Labour/s & Dealer/s of Labouradda, Thekedaar/s listed with Labouradda. All the Users are cautioned that all and any information of whatsoever nature provided or received from the Labour/s & Dealer/s of Labouradda, Thekedaar/s, is taken in good faith, without least suspecting the bonafides of the Labour/s & Dealer/s of Labouradda, Thekedaar/s and Labouradda does not confirm, does not acknowledge, or subscribe to the claims and representation made by the Labour/s & Dealer/s of Labouradda, Thekedaar/s listed with Labouradda. Further, Labouradda is not at all responsible for any act of the Labour/s & Dealer/s of Labouradda, Thekedaar/s listed at Labouradda.
					We make no representation or warranty of any kind to anyone, express or implied for accuracy, adequacy, validity, reliability or completeness of the information provided directly by these dealers / Labours to a service seeking consumer. We do not / have not investigated or checked for accuracy, adequacy, validity, reliability, availability or completeness of the information shared by the dealers / Labours. The Consumers using our platforms consent to use services of these Job providing Labours sourced through our authorized dealers / mobile application / Websites / Facebook / Call center and consumer’s reliance on information provided directly to consumers by the dealers / labours is solely at own risk of consumers. We do not monitor or supervise these dealer’s / labours directly or indirectly. We recommend consumers to supervise them closely to avoid any inconvenience or damage to property. The rates quoted by these dealers or the labours directly for their services that they offer has to be validated by consumers using own discretion.  Consumers, dealers, thekedars & the Labours are free to accept or reject rates and services for which they are not bound by our terms in any way. Under no circumstance shall we have any liability to consumers,dealers, thekedaars and labours for any loss or damage of any kind incurred as a result of use or selection of any skilled or unskilled workers vide our Mobile applications. OTAF Overseas Private Limited does not charge any money directly to service seeking consumers of labours for the connectivity to nearest labours.</p>

					<!-- Limitation of Liability -->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>Limitation of Liability</strong></h2>
					<p>IN NO EVENT SHALL LABOURADDA, OTAF OVERSEAS PVT LTD, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES WHATSOEVER RESULTING FROM ANY</p>

					<ol>
						<li>ERRORS, MISTAKES, OR INACCURACIES OF CONTENT,</li>
						<li>PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR SERVICE,</li>
						<li>ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN,</li>
						<li>ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR SERVERS,</li>
						<li>ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE, WHICH MAY BE TRANSMITTED TO OR THROUGH OUR SERVICE BY ANY THIRD PARTY,</li>
						<li>ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF YOUR USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE LABOURADDA CLIENT, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT THE COMPANY IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, AND/OR</li>
						<li>THE DISCLOSURE OF INFORMATION PURSUANT TO THESE TERMS OF SERVICE OR PRIVACY POLICY. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION.</li>
					</ol>

					<p>YOU SPECIFICALLY ACKNOWLEDGE THAT LABOURADDA SHALL NOT BE LIABLE FOR USER SUBMISSIONS OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY AND THAT THE RISK OF HARM OR DAMAGE FROM THE FOREGOING RESTS ENTIRELY WITH YOU.</p>

					<!-- Indemnity -->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>Indemnity</strong></h2>
					<p>You agree to defend, indemnify and hold harmless Labouradda and OTAF officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees) arising from:</p>

					<ol>
						<li>your use of and access to the Labouradda Platform;</li>
						<li>your violation of any term of these Terms of Service;</li>
						<li>your violation of any third party right, including without limitation any copyright, property, or privacy right; or</li>
						<li>any claim that one of your Ratings and/or Reviews or Comments caused damage to a third party. This defense and indemnification obligation will survive these Terms of Service and your use of the Labouradda Platform.</li>
					</ol>


					<!-- Ability to Accept Terms of Service -->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>Ability to Accept Terms of Service</strong></h2>
					<p>Labouradda Platform. Only adults, who are at least eighteen (18) years of age, are eligible to use our service, whether for personal use or on behalf of a business. If you are an individual, you must be fully competent to enter into and to comply with the terms, conditions, obligations, representations, and warranties set forth in these Terms of Use. By using this service, you represent and warrant that you have the right, authority, and capacity to enter into these Terms of Use and can abide by all of the terms and conditions set forth therein.</p>

					<!-- Assignment-->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>Assignment</strong></h2>
					<p>These Terms of Service, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by Labouradda/OTAF Overseas Pvt Ltd without restriction.</p>

					<!-- Miscellaneous-->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>Miscellaneous</strong></h2>
					<p>You agree that we may assign these Terms of Use without prior notice to a successor entity in the event of a merger, acquisition, or sale of all or part of our business. No waiver of any breach of the Terms of Use, no matter how long continuing or how often repeated will be deemed a waiver of any subsequent breach, nor shall any delay or omission to exercise any right, power, or privilege hereunder be deemed a waiver of such right, power, or privilege. If any section of these Terms of Use is held to be unenforceable or in conflict with the law of any jurisdiction, the validity of the remaining paragraphs shall not be affected by such holding. The meaning of that section shall be construed to the extent feasible to render the section enforceable and to give effect to the Parties' intentions as reflected in the section. If no feasible interpretation would save such section, it is to be severed from the remainder of these Terms of Use, which are to remain in full force and effect. The Terms of Use constitute the entire agreement between you and us with respect to the subject matter set forth herein. The section headings and subheadings contained in these Terms of Use are included for convenience only and shall not limit or otherwise affect these Terms of Use.</p>

					<!-- GOVERNING LAW-->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>GOVERNING LAW</strong></h2>
					<p>These Terms will be governed by and construed in accordance with the Indian laws, without giving effect to its conflict of laws' provisions or your actual state or country of residence, and you agree to submit to personal jurisdiction in India. Courts at Lucknow will have the exclusive jurisdiction. You are responsible for compliance with applicable laws. If for any reason a court of competent jurisdiction finds any provision or portion of the Terms to be unenforceable, the remainder of the Terms will continue in full force and effect. Labouradda reserves the right to investigate complaints or reported violations of these Terms and to take any action we deem necessary and appropriate. Such action may include reporting any suspected unlawful activity to law enforcement officials, regulators, or other third parties. In addition, we may take action to disclose any information necessary or appropriate to such persons or entities relating to user profiles, e-mail addresses, usage history, posted materials, IP addresses and traffic information. Labouradda reserves the right to seek all remedies available at law and in equity for violations of these Terms.</p>

					<!-- Privacy Policy -->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>GOVERNING LAW</strong></h2>
					<p>In the course of registering for and availing various services we provide from time to time through our website www.labouradda.net ("Website", telephone search, Social Media, SMS and APP) or any other medium in which Labouradda may provide services (collectively referred to as "Media or Platforms") you may be required to give your name, residence address, workplace address, email address, date of birth, educational qualifications and similar Personal Information ("Personal Information"). The Personal Information is used for three general purposes: to customize the content you see, to fulfill your requests for certain services, and to contact you about our services via including but not limited to email's, sms's and other means of communication. Unless otherwise stated explicitly, this Policy applies to Personal Information as disclosed on any of the Media.
					<br><br>

					We are committed to protecting the privacy and confidentiality of all Personal Information that you may share as a user of Media In furtherance thereof, we have this policy to demonstrate our good faith.
					<br><br>

					This policy does not apply to the practices of organizations that we do not own or to people that we do not employ or manage.
					<br><br>
					Personal Information will be kept confidential and will be used for our research, marketing, and strategic client analysis objectives and other internal business purposes only. We do not sell or rent Personal Information except that in case you are a customer of our search services through any of the Media, your Personal Information shall be shared with our subscribers/advertisers and you shall be deemed to have given consent to the same. Further, the subscribers / advertisers/ Call center executives of Labouradda/labours/dealers of labouradda / thekdaars who are listed with us, may call you , based on the query or enquiry that you make with us, enquiring about any
					</p>

					<ul>
						<li>Product / Service or</li>
						<li>Product / Service of any subscriber / advertiser or</li>
						<li>Product / Service of any particular subscriber / advertise or</li>
						<li>subscribers / advertisers/ labours/dealers of labouradda / thekdaars.</li>
					</ul>

					<p>We will share Personal Information only under one or more of the following circumstances: - If we have your consent or deemed consent to do so - If we are compelled by law (including court orders) to do so</p>
					

					<p>In furtherance of the confidentiality with which we treat Personal Information we have put in place appropriate physical, electronic, and managerial procedures to safeguard and secure the information we collect online.</p>

					<p>We give you the ability to edit your account information and preferences at any time. To protect your privacy and security, we will also take reasonable steps to verify your identity before granting access or making corrections.</p>

					<p>You acknowledge that you are disclosing Personal Information voluntarily. Prior to the completion of any registration process on our website/Social Media / Mobile App or prior to availing of any services offered on our website if you wish not to disclose any Personal Information you may refrain from doing so; however if you don't provide information that is requested, it is possible that the registration process would be incomplete and/or you would not be able to avail of the our services.</p>

					<p>If you are our corporate consumer of Labour or Labouradda Platforms/ media, it is possible that we have entered into a contract with you for non-disclosure of confidential information. This Policy shall not affect such a contract in any manner.</p>

					<p>If you have questions or concerns about these privacy policies; please send us an email at care@labouradda.net</p>


					<!-- Privacy Notice-->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>Privacy Notice</strong></h2>
					<p>Labouradda is committed to protecting the privacy and confidentiality of all Personal Information that you may share as a user of Media. In furtherance thereof, we have this policy to demonstrate our good faith.
					This Privacy Policy is incorporated into and is subject to the Labouradda Terms of Service. Your use of the Labouradda Site, Labouradda Software and the Labouradda Platform and any personal information you provide remains subject to the terms of this Privacy Policy and our Terms of Service.

					<br>
					<strong>What Does This Privacy Policy Cover ?</strong> This Privacy Policy is part of Labouradda's Terms of Service and covers the treatment of user information, including personally identifying information, obtained by Labouradda, including information obtained when you access the Labouradda Site, use the Labouradda Platform or any other software provided by Labouradda.
					</p>

					<!-- The Information Labouradda Collects-->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>The Information Labouradda Collects</strong></h2>
					<p>Labouradda may obtain the following types of information from or concerning you or your mobile phone device, which may include information that can be used to identify you as specified below ("Personally Identifying Information") :
					</p>

					<ul>
						<li>
							You provide certain Personally Identifiable Information, such as your mobile phone number, and mobile device information to Labouradda when choosing to participate in various uses of the Labouradda Platform, such as registering as a user, and viewing ratings of contacts in your address book. In order to provide the Labouradda Platform, Labouradda will periodically access your address book or contact list on your mobile phone to locate the mobile phone numbers that have been used to avail Labouradda Platform and to provide ratings of establishments we have received from users of these mobile numbers. Labouradda may access your location information to provide search results based on your geo location. This allows the software to provide relevant search results. Location data gathered from a mobile phone is used only to provide search results and is not used in any other manner whatsoever.
						</li>
					</ul>


					<!-- The Information Labouradda Does Not Collect -->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>The Information Labouradda Does Not Collect</strong></h2>
					<p>Labouradda does not collect emails, addresses or other contact information from its users' mobile address book or contact lists other than name, mobile phone numbers and location. Labouradda does not store historical location information of users in any form or manner at its end, except for the last known location from which the Labouradda software was accessed in case of non availability of current location data. Labouradda App integrates with facebook SDK, Android SDK and may send aggregate usage statistics to facebook from time to time. Usage of information sent to facebook is governed by Facebook's data usage policies which can be found at <a href="https://www.facebook.com/about/privacy" target="_blank">www.facebook.com/about/privacy.</a> </p>


					<!-- The Way Labouradda Uses Information -->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>The Way Labouradda Uses Information</strong></h2>
					<p>If you submit Personally Identifiable Information to us through the Labouradda WebSite, or any Labouradda Platform, then we use your personal information to operate, maintain, and provide to you the features and functionality of the Labouradda Website and Labouradda Platforms. In particular, your mobile phone number is essential to your use of the Labouradda Platform and will be retained. Your name (as it is saved in other user's mobile phone address book or contact list) may be displayed to other users if they tag your mobile number and access your ratings in the App. For more information on our ratings feature, please read the note below : <br><br>
					Labouradda will use your mobile number and contacts list to identify friends in your network who have rated establishments and/or are users of Labouradda Platform. Labouradda collects ratings in the following ways :</p>

					<ul>
						<li>When a user calls our service and is prompted to rate an establishment</li>
						<li>When a user rates establishments on the website or mobile site or Applications</li>
					</ul>

					<p><strong>Where are the ratings shown ?</strong> Ratings are shown in the following ways on Labouradda :</p>

					<ul>
						<li>In SMS when user asks for information by calling the Labouradda Platform</li>
						<li>Ratings are displayed on various places on the website, mobile site and mobile applications in pages such as the overall ratings count page, search results pages, company details pages etc. User information such as mobile phone number is masked and personally identifiable information is not displayed unless user is registered with Labouradda and is accessing the tag friends feature.</li>
						<li>Ratings are shown in the Labouradda Mobile APP available across Labouradda platforms where users can access ratings of service providers.</li>
					</ul>


					<!-- Benefits -->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>Benefits</strong></h2>
					<p>Your contacts list will allow Labouradda to provide you with ratings given by your friends and help make the experience on Labouradda platforms even better. Your friends' ratings will allow you to make a better decision about choosing a product/service/establishment on Labouradda.</p>

					<!-- How Labouradda uses your information -->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>How Labouradda uses your information</strong></h2>
					<p>Labouradda will provide users with a privacy settings option that will allow the user to choose appropriate privacy levels. We do not use your mobile phone number or other Personally Identifiable Information to send commercial or marketing messages without your consent or except as part of a specific program or feature for which you will have the ability to opt-in or opt-out. We may use cookies and log file information to :</p>

					<ol>
						<li>Remember information so that you will not have to re-enter it during your visit or the next time you use Labouradda;</li>
						<li>provide custom, personalized content and information;</li>
						<li>monitor individual and aggregate metrics such as total number of visitors, pages viewed, etc.; and</li>
						<li>track your entries, submissions, views and such.</li>
					</ol>



					<!-- When Labouradda Discloses Information -->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>How Labouradda uses your information</strong></h2>
					<p>Other users of the Labouradda Platform may see your ratings submissions in a way that is consistent with the use of the Labouradda Platform. For example, a rating of "Labouradda Dealer" on Labouradda Mobile App will be available to every user of the Labouradda Platform who has that mobile phone number in their mobile phone's address book .<br>
					We do not sell or share your Personally Identifiable Information (such as mobile phone number) with other third-party companies for their commercial or marketing use without your consent or except as part of a specific program or feature for which you will have the ability to opt-in or opt-out. We may share your Personally Identifiable Information with third party service providers to the extent that it is reasonably necessary to perform, improve or maintain the Labouradda Platform.
					</p>


					<!-- Your Choices -->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>You Choices</strong></h2>
					<p>You may, of course, decline to submit Personally Identifiable Information through the Labouradda Platform, in which case Labouradda may not be able to provide certain services to you. If you do not agree with our Privacy Policy or Terms of Service, please delete your account and uninstall the Labouradda mobile application; your continued usage of the Labouradda Platform will signify your assent to and acceptance of our Privacy Policy and Terms of Service. To protect your privacy and security, we take reasonable steps (such as SMS authentication in certain cases) to verify your identity before registering your mobile phone number and granting you access to the Labouradda Platform. Please contact Labouradda via email to privacy at labouradda.net or available web forms with any questions or comments about this Privacy Policy, your personal information, your consent, or your opt-in or opt-out choices.
					</p>


					<!-- Third-party Advertisers, Links to Other Sites -->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>Third-party Advertisers, Links to Other Sites</strong></h2>
					<p>Labouradda is currently ad-free and we hope to keep it that way forever. We have no intention to introduce advertisement into the product, but if we ever do, we will update this section.
					</p>


					<!-- Our Commitment to Data Security-->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>Our Commitment to Data Security</strong></h2>
					<p>Labouradda uses commercially reasonable physical, managerial, and technical safeguards to preserve the integrity and security of your personal information. We cannot, however, ensure or warrant the security of any information you transmit to Labouradda and you do so at your own risk.
					</p>


					<!-- Consent To Push Notification:-->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>Consent To Push Notification</strong></h2>
					<p>You agree and confirm that any review, rating and comments, including any other content or data therein, that you submit/post on Labouradda platforms viz. WEB, WAP, APP & Phone etc. such details as per Labouradda's discretion will be shared with the users of Labouradda's Platform.
					</p>

					<!-- YOUR ACCEPTANCE OF THIS AGREEMENT: -->
					<h2 class="d-flex align-items-center mb-4 text-primary"><strong>YOUR ACCEPTANCE TO THIS AGREEMENT</strong></h2>
					<p>This is an agreement between you ("you", " your" "caller" or "user") and OTAF OVERSEAS Private Limited. ("Labouradda" "we," or "our") that governs your use of the search, booking services or any other services offered by Labouradda through its website www.labouradda.net ("Website"), telephone search, SMS, WAP or any other medium (collectively "Platforms" ). When you access, use or book any orders using any of the Platforms you agree to be bound by these Terms and Conditions ("Terms").</p>

					<ol>
						<strong><li>Interpretation</li></strong>
						<p>"Agreement" is for the purposes of placing an order of service through its service providers registered/listed with Labouradda as described in this agreement. All the orders/enquiries placed by you through its website www.labouradda.net ("Website") or Labouradda Mobile Application , telephone search, SMS, WAP or any other medium, will be forwarded by Labouradda to the service providers listed with us, for further processing of your orders. <br>
						"Intellectual Property Rights" Includes all rights in respect of copyright, trademarks, patents, designs, protection of confidential information and circuit layouts, whether arising under statute or otherwise. <br>
						"Order" means an enquiries/ booking request placed by you through Labouradda platforms which in turn will be forwarded to respective Service Providers (Labours / Dealers of Labouradda/ Thekedaar) listed with Labouradda. <br>
						"Product List" means the list of services displayed on the labouradda.net website or Mobile Application as amended from time to time.
						</p>

						<strong><li>Applicability</li></strong>
						<p>The terms of use will be applicable between You and Labouradda once you have placed the order for goods as described in this agreement.</p>

						<strong><li>Placement of Order</li></strong>
						<p>You have the option of placing the order by calling to Labouradda Call Centre Number and/or by using the booking facility provided on the web, wap or by any other means as introduced by Labouradda from time to time.
						Labouradda collects customer orders and forwards them to the service providers (Labours / Dealers of Labouradda/ Thekedaar) who may or may not choose to complete the order.
						</p>

						<strong><li>Completed Orders</li></strong>
						<p>You must complete or give requisite details for completing an order form for the purposes of booking your order. You warrant that all information and data provided by you in the order form is accurate, complete and up to date. If you are placing an order through phone then in that event your order is deemed to be completed once the details are filled by the Labouradda Customer Care executive and in case you are placing an online order through Labouradda website or wap service then it is deemed to be completed once the details are filled online in the order form.
						</p>

						<strong><li>Cancellation and Modification</li></strong>
						<p>Cancellation or modification of any bookings made through any Labouradda platforms shall be strictly in accordance with the service providers(Labours / Thekedaar/dealer of labouradda) modification and cancellation terms to be decided between service providers and consumers, including with respect to refund. You may directly contact the respective service provider and/or Labouradda Call Centre for processing any requests pertaining to cancellation or modification. The cancellation and modification request made by you to Labouradda Call Centre will be forwarded to the respective service provider for its resolution. The rates quoted by these service providers dealers or the labours directly for their services that they offer has to be validated by consumers using own discretion.  Consumers, dealers, thekedars & the Labours are free to accept or reject rates and services for which they are not bound by our terms in any way. Under no circumstance shall we have any liability to consumers,dealers, thekedaars and labours for any loss or damage of any kind incurred as a result of use or selection of any skilled or unskilled workers vide our Mobile applications. OTAF Overseas Private Limited does not charge any money directly to service seeking consumers of labours for the connectivity to nearest labours.
						</p>
					</ol>
				</div>
			</div>
		</section>



<?php include "includes/footer.php" ?>